class TestClipboard
  def setup_816: () -> nil

  def test_clipboard_copy_region: () -> nil

  def test_clipboard_kill_line: () -> nil

  def test_clipboard_kill_line_read_only: () -> nil

  def test_clipboard_kill_region: () -> nil

  def test_clipboard_kill_region_read_only: () -> nil

  def test_clipboard_kill_word: () -> nil

  def test_clipboard_kill_word_read_only: () -> nil

  def test_clipboard_yank: () -> nil

  def test_clipboard_yank_pop: () -> nil
end
