class TestServer
  def setup_936: () -> String

  def test_eval: () -> nil

  def teardown_952: () -> Integer

  def test_multipel_server_start: () -> Textbringer::Server::ExistError

  def test_server_sock_mode_empty_options: () -> nil

  def test_server_sock_mode_no_options: () -> nil

  def test_server_sock_mode_specified_options: () -> nil

  def test_unlink_dead_socket: () -> nil

  def test_visit_file: () -> nil
end
