class TestIsearch
  def test_isearch_abort: () -> nil

  def test_isearch_backward: () -> nil

  def test_isearch_exit: () -> nil

  def test_isearch_forward: () -> nil

  def test_isearch_forward_case: () -> nil

  def test_isearch_forward_fail: () -> nil

  def test_isearch_forward_repeat: () -> nil

  def test_isearch_mark_independent_from_visible_mark: () -> nil

  def test_isearch_mark_set_and_cleanup: () -> nil

  def test_isearch_toggle_input_method: () -> nil

  def test_isearch_yank_word_or_char: () -> nil
end
