class TestWindows
  def test_bury_buffer: () -> nil

  def test_delete_other_windows: () -> nil

  def test_delete_window: () -> nil

  def test_enlarge_window: () -> nil

  def test_kill_buffer: () -> nil

  def test_list_buffers: () -> nil

  def test_other_window: () -> nil

  def test_recenter: () -> nil

  def test_resize: () -> nil

  def test_scroll_down: () -> RangeError

  def test_scroll_up: () -> RangeError

  def test_shrink_window: () -> nil

  def test_shrink_window_if_larger_than_buffer: () -> nil

  def test_split_window: () -> Textbringer::EditorError

  def test_switch_to_buffer: () -> nil
end
