module Curses
  def self.colors: () -> Integer

  def self.init_pair: (*Integer) -> nil

  def self.color_pair: (Integer) -> Integer

  def self.lines: () -> Integer

  def self.cols: () -> Integer

  def self.doupdate: (*nil) -> nil

  def self.colors=: (Integer) -> Integer

  def self.beep: (*nil) -> nil

  def self.set_key_modifiers: (Integer) -> Integer

  def self.save_key_modifiers: (bool) -> nil

  def self.get_key_modifiers: () -> Integer

  def self.assume_default_colors: (Integer, Integer) -> Array[untyped]

  def self.default_colors: () -> Array[untyped]

  def self.init_screen: (*nil) -> nil

  def self.noecho: (*nil) -> nil

  def self.raw: (*nil) -> nil

  def self.nonl: (*nil) -> nil

  def self.has_colors?: () -> bool

  def self.start_color: (*nil) -> nil

  def self.use_default_colors: (*nil) -> nil

  def self.echo: (*nil) -> nil

  def self.noraw: (*nil) -> nil

  def self.nl: (*nil) -> nil

  def self.close_screen: (*nil) -> nil

  def self.lines=: (Integer) -> Integer

  def self.cols=: (Integer) -> Integer
end

class Textbringer::TestCase
  def setup_784: () -> Textbringer::Buffer

  def teardown_800: () -> nil

  def omit_on_windows: () -> nil
                     | () -> Textbringer::Server::ExistError

  def on_windows?: () -> nil

  def buffer: () -> Textbringer::Buffer

  def push_keys: (String) -> Array[untyped]
               | (Array[untyped]) -> Array[untyped]

  def mkcdtmpdir: () -> nil
                | () -> SystemExit
end

class Textbringer::FakeController
  def initialize: (*nil) -> void

  def read_event: () -> String
                | () -> Integer
                | () -> nil
                | () -> Symbol

  def call_read_event_method: (Symbol) -> String
                            | (Symbol) -> Integer
                            | (Symbol) -> nil
                            | (Symbol) -> Symbol

  def call_next_block: () -> Thread::Queue
end

class Textbringer::Window
  def self.setup_for_test: () -> Array[untyped]

  def self.clear_list: () -> Array[untyped]

  def self.lines=: (Integer) -> Integer

  def self.columns=: (Integer) -> Integer
end

class Textbringer::FakeCursesWindow
  def initialize: (Integer, Integer, Integer, Integer) -> void

  def method_missing: (Symbol, *bool) -> nil
                    | (Symbol, *Integer) -> nil
                    | (Symbol, *nil) -> nil

  def erase: () -> Array[untyped]

  def setpos: (Integer, Integer) -> Integer

  def addstr: (String) -> Integer

  def get_char: () -> nil
              | () -> String
              | () -> Integer

  def resize: (Integer, Integer) -> Integer

  def move: (Integer, Integer) -> Integer

  def push_key: (String) -> Array[untyped]
              | (Integer) -> Array[untyped]

  def maxy: () -> Integer
end

class Textbringer::FakeCursesPad
  def initialize: (Integer, Integer) -> void

  def method_missing: (Symbol, *bool) -> nil
                    | (Symbol, *nil) -> nil

  def erase: () -> Array[untyped]

  def attrset: (Integer) -> Integer

  def setpos: (Integer, Integer) -> Integer

  def addstr: (String) -> Integer

  def noutrefresh: (Integer, Integer, Integer, Integer, Integer, Integer) -> nil
end
