class TestUtils
  def test_gsub: () -> nil

  def test_hooks: () -> nil

  def test_message: () -> nil

  def test_read_buffer: () -> nil

  def test_read_char: () -> Textbringer::EditorError

  def test_read_command_name: () -> nil

  def test_read_event: () -> nil

  def test_read_file_name: () -> nil

  def test_read_from_minibuffer: () -> Textbringer::EditorError

  def test_read_key_sequence: () -> Textbringer::EditorError

  def test_read_object: () -> nil

  def test_read_single_char: () -> nil

  def test_set_transient_map: () -> nil

  def test_show_exception: () -> SystemExit

  def test_y_or_n?: () -> nil

  def test_yes_or_no?: () -> nil
end
