class TestCompletionPopup
  def setup: () -> Textbringer::CompletionPopup

  def test_accept: () -> nil

  def teardown: () -> nil

  def test_accept_when_not_visible: () -> nil

  def test_cancel: () -> nil

  def test_close: () -> nil

  def test_current_item: () -> nil

  def test_current_item_when_empty: () -> nil

  def test_hide: () -> nil

  def test_items_with_detail: () -> nil

  def test_select_next: () -> nil

  def test_select_next_when_not_visible: () -> nil

  def test_select_previous: () -> nil

  def test_select_previous_when_not_visible: () -> nil

  def test_show_with_empty_items: () -> nil

  def test_show_with_items: () -> nil

  def test_show_with_prefix: () -> nil

  def test_singleton_instance: () -> nil

  def test_visible_when_not_shown: () -> nil
end
