class TestWindow
  def setup_1280: () -> Textbringer::Buffer

  def test_echo_area_redisplay:

  def assert_window: () -> nil

  def test_has_input?: () -> nil

  def test_read_event: () -> nil

  def test_read_event_nonblock: () -> nil

  def test_redisplay: () -> nil

  def test_redisplay_devanagari:

  def test_redisplay_diacritical_marks:

  def test_redisplay_escape_ambiwidth:

  def test_redisplay_escape_binary:

  def test_redisplay_escape_utf8:

  def test_redisplay_hangul:

  def test_redisplay_mode_line: () -> Textbringer::OverwriteMode

  def test_redisplay_ruby_mode:

  def test_redisplay_tabs:

  def test_redisplay_variation_selectors:

  def test_s_current: () -> nil

  def test_s_readraw: () -> nil

  def test_s_set_default_colors: () -> nil

  def test_s_start: () -> nil

  def test_wait_input: () -> nil
end
