class TestBuffer
  def setup_1144: () -> Integer

  def test_after_change_functions_delete: () -> nil

  def test_after_change_functions_delete_region: () -> nil

  def test_after_change_functions_insert: () -> nil

  def test_after_change_functions_not_called_during_undo: () -> nil

  def test_attributes: () -> nil

  def test_backward_line: () -> nil

  def test_backward_word: () -> nil

  def test_beginning_of_line: () -> nil

  def test_beginning_of_line?: () -> nil

  def test_binary: () -> nil

  def test_capitalize_word: () -> nil

  def test_char_after: () -> nil

  def test_char_before: () -> nil

  def test_clear: () -> nil

  def test_convert_word: () -> nil

  def test_copy_region:

  def test_current?: () -> nil

  def test_current_symbol: () -> nil

  def test_delete_char: () -> nil

  def test_delete_char_at_bob: () -> nil

  def test_delete_char_at_eob: () -> nil

  def test_delete_char_backward: () -> nil

  def test_delete_char_forward: () -> nil

  def test_delete_char_over_bob: () -> nil

  def test_delete_char_over_eob: () -> nil

  def test_delete_region: () -> nil

  def test_downcase_word: () -> nil

  def test_dump: () -> nil

  def test_editing: () -> nil

  def test_end_of_line: () -> nil

  def test_end_of_line?: () -> nil

  def test_file_format: () -> ArgumentError

  def test_file_modified?: () -> nil

  def test_find_or_new: () -> nil

  def test_forward_char: () -> nil

  def test_forward_line: () -> nil

  def test_forward_word: () -> nil

  def test_gap_to_user: () -> nil

  def test_get_line_and_column: () -> nil

  def test_goto_char: () -> nil

  def test_goto_line: () -> nil

  def test_gsub: () -> nil

  def test_gsub_with_block: () -> nil

  def test_indent_to: () -> nil

  def test_insert: () -> Textbringer::EditorError

  def test_insert_not_to_modify_arg: () -> nil

  def test_insert_to_s: () -> nil

  def test_inspect: () -> nil

  def test_kill_line: () -> RangeError

  def test_kill_region: () -> nil

  def test_kill_word: () -> RangeError

  def test_looking_at?: () -> nil

  def test_mark: () -> Textbringer::EditorError

  def test_newline: () -> nil

  def test_next_line: () -> nil

  def test_next_line_multibyte: () -> nil

  def test_next_line_tab: () -> nil

  def test_nkf_detect_encoding: () -> nil

  def test_point_min_max: () -> nil

  def test_pos_to_line_and_column: () -> nil

  def test_previous_line: () -> nil

  def test_re_search_backward: () -> Textbringer::SearchError

  def test_re_search_forward: () -> nil

  def test_read_only: () -> Textbringer::ReadOnlyError

  def test_replace: () -> nil

  def test_replace_regexp_forward: () -> nil

  def test_s_auto_detect_encodings: () -> nil

  def test_s_display_width: () -> nil

  def test_s_dump_unsaved_buffers: () -> nil

  def test_s_each: () -> nil

  def test_s_find_file: () -> nil

  def test_s_last: () -> nil

  def test_s_list: () -> nil

  def test_s_minibuffer: () -> nil

  def test_s_names: () -> nil

  def test_s_new_buffer: () -> nil

  def test_s_other: () -> nil

  def test_save_as: () -> nil

  def test_save_as_dir: () -> nil

  def test_save_as_fail: () -> nil

  def test_save_ascii_only: () -> nil

  def test_save_binary: () -> nil

  def test_save_binary_with_nkf: () -> nil

  def test_save_dos: () -> nil

  def test_save_euc_jp: () -> nil

  def test_save_excursion: () -> nil

  def test_save_iso2022jp: () -> nil

  def test_save_mac: () -> nil

  def test_save_no_file_name: () -> Textbringer::EditorError

  def test_save_utf8: () -> nil

  def test_save_windows31j: () -> nil

  def test_set_name: () -> nil

  def test_substring: () -> nil

  def test_to_s: () -> nil

  def test_transpose_chars: () -> Textbringer::Buffer

  def test_undo: () -> Textbringer::EditorError

  def test_undo_composite_edit: () -> nil

  def test_undo_limit: () -> Textbringer::EditorError

  def test_undo_merge: () -> nil

  def test_upcase_word: () -> nil

  def test_visible_mark: () -> nil

  def test_yank: () -> Integer
end
