class TestCMode
  def setup_1064: () -> Textbringer::Buffer

  def test_compile: () -> nil

  def test_default_compile_command: () -> nil

  def test_indent_line_brace: () -> nil

  def test_indent_line_comments: () -> nil

  def test_indent_line_comments_at_top_level: () -> nil

  def test_indent_line_digraph: () -> nil

  def test_indent_line_labels: () -> nil

  def test_indent_line_paren: () -> nil

  def test_indent_line_preprocessing_derective: () -> nil

  def test_indent_line_top_level: () -> nil

  def test_indent_line_unmatch: () -> Textbringer::EditorError

  def test_lex: () -> nil

  def test_lex_empty_token: () -> Textbringer::EditorError

  def test_lex_identifiers: () -> nil

  def test_lex_keywords: () -> nil

  def test_lex_punctuators: () -> nil

  def test_lex_string_literals: () -> nil

  def test_lex_wide_string_literals: () -> nil

  def test_symbol_pattern: () -> nil
end
