#!/usr/bin/env ruby

require "textbringer"

include Textbringer
include Commands

def load_user_config
  config_file = File.expand_path("~/.tb")
  begin
    load(config_file)
  rescue LoadError
  end
end

Controller.current = Controller.new
Buffer.minibuffer.keymap = MINIBUFFER_LOCAL_MAP
Window.start do
  Window.echo_area.buffer = Buffer.minibuffer
  message("Type C-x C-c to exit Textbringer")
  begin
    buffer = Buffer.new_buffer("*scratch*")
    switch_to_buffer(buffer)
    load_user_config
    if ARGV.size > 0
      ARGV.each do |arg|
        find_file(arg)
      end
    end
  rescue Exception => e
    handle_exception(e)
  end
  Window.redisplay
  trap(:CONT) do
    Window.echo_area.redraw
    Window.windows.each(&:redraw)
    Window.update
  end
  loop do
    Controller.current.command_loop(TOP_LEVEL_TAG)
    Window.redisplay
  end
end
