#!/usr/bin/env ruby

require "warning"
require "optparse"

Warning.ignore(/already initialized constant /)
Warning.ignore(/previous definition of /)
Warning.ignore(/not part of the default gems/)

require "textbringer"

include Textbringer
include Commands

# Parse command-line options
opts = OptionParser.new do |o|
  o.banner = "Usage: txtb [options] [files...]"

  o.on("--engine ENGINE", "Select editing engine: emacs (default), cua") do |e|
    CONFIG[:engine] = e.to_sym
  end

  o.on("-h", "--help", "Show this help message") do
    puts o
    exit
  end

  o.on("-v", "--version", "Show version") do
    puts "Textbringer #{Textbringer::VERSION}"
    exit
  end
end
files = opts.parse!(ARGV)

def load_user_config(path)
  config_file = File.expand_path(path)
  begin
    load(config_file)
  rescue LoadError
  end
end

unless STDIN.tty?
  STDERR.puts("txtb: standard input is not a tty")
  exit 1
end

Controller.current = Controller.new
begin
  Window.start do
    load_user_config("~/.textbringer/init.rb")
    $stdout = DefaultOutput.new
    begin
      # Initialize the engine
      Controller.current.engine.setup

      transient_mark_mode(true)
      Window.echo_area.clear_message
      Plugin.load_plugins
      load_user_config("~/.textbringer.rb")
      ruby_mode
      if files.size > 0
        files.each do |arg|
          find_file(arg)
        end
      end
      if Buffer.dumped_buffers_exist?(CONFIG[:buffer_dump_dir])
        Window.redisplay
        if yes_or_no?("Dumped buffers found; restore them?")
          buffers = Buffer.load_dumped_buffers(CONFIG[:buffer_dump_dir])
          switch_to_buffer(buffers.last)
        end
      end
    rescue Exception => e
      show_exception(e)
    end
    Window.redisplay
    begin
      trap(:CONT) { Window.redraw }
    rescue ArgumentError
    end
    begin
      loop do
        Controller.current.command_loop(TOP_LEVEL_TAG)
        Window.redisplay
      end
    rescue Exception => e
      if !e.is_a?(SystemExit)
        Buffer.dump_unsaved_buffers(CONFIG[:buffer_dump_dir])
      end
      raise
    end
  end
ensure
  Controller.current.close
end
