class TestTCodeInputMethod
  def setup_1008: () -> Textbringer::Buffer

  def test_bushu_composition: () -> nil

  def test_bushu_composition_failure: () -> nil

  def test_insert_direct: () -> nil

  def test_insert_kanji: () -> nil

  def test_mazegaki_conversion_automatic_finish: () -> nil

  def test_mazegaki_conversion_cancel: () -> nil

  def test_mazegaki_conversion_failure: () -> nil

  def test_mazegaki_conversion_from_many: () -> nil

  def test_mazegaki_conversion_from_one: () -> nil

  def test_mazegaki_conversion_from_two: () -> nil

  def test_mazegaki_conversion_pagination: () -> nil

  def test_mazegaki_conversion_with_inflection: () -> nil

  def test_relimit_left: () -> nil

  def test_relimit_right: () -> nil

  def test_show_stroke: () -> nil
end
