name: ubuntu

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: Run test
      uses: koki-develop/hub-purge-action@c608e39abca23026c802f44643cffccc123a826f # v1.0.3
        with:
          repository: shugo/textbringer
          branch: main
          path: |
            README.md
            README.ja.md
