name: purge hub test

on: [push]

jobs:
  purge_cache:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: Purge cache
      shell: bash
      run: |
        urls=$(curl -sLk "https://github.com/${{ github.repository_owner }}/${{ github.event.repository.name }}/tree/main" | grep -Eo "(http|https)://camo.githubusercontent.com[a-zA-Z0-9./?=_%:-]*")
        while IFS= read -r url; do echo -e "\nPurge $url"; curl -X PURGE "$url"; done <<< "$urls"
